/**
 * Generated icon data from SVG files
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-icons.js
 */

export interface SvgNode {
  type: 'path' | 'circle' | 'rect' | 'ellipse' | 'line' | 'polyline' | 'polygon' | 'g';
  props: Record<string, any>;
  children?: SvgNode[];
}

export interface SvgData {
  viewBox: string;
  children: SvgNode[];
}

export const SVG_CONTENT: Record<string, SvgData> = {
  "ALERT": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "circle",
        "props": {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      }
    ]
  },
  "BELL": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"
        }
      },
      {
        "type": "path",
        "props": {
          "d": "M13.73 21a2 2 0 0 1-3.46 0"
        }
      }
    ]
  },
  "CONFIRM": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "polyline",
        "props": {
          "points": "20 6 9 17 4 12"
        }
      }
    ]
  },
  "CUSTOM": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M12 2v20M2 12h20"
        }
      },
      {
        "type": "circle",
        "props": {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      }
    ]
  },
  "DIALOG": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"
        }
      }
    ]
  },
  "HEART": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"
        }
      }
    ]
  },
  "HOME": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
        }
      },
      {
        "type": "polyline",
        "props": {
          "points": "9 22 9 12 15 12 15 22"
        }
      }
    ]
  },
  "INPUT": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M12 3v18"
        }
      },
      {
        "type": "path",
        "props": {
          "d": "M6 9h12M6 15h12"
        }
      }
    ]
  },
  "LAYERS": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "polyline",
        "props": {
          "points": "12 22 12 12"
        }
      },
      {
        "type": "polyline",
        "props": {
          "points": "20 7 12 12 4 7"
        }
      }
    ]
  },
  "PACKAGE": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"
        }
      },
      {
        "type": "polyline",
        "props": {
          "points": "3.27 6.96 12 12.01 20.73 6.96"
        }
      }
    ]
  },
  "SETTINGS": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M12 1v6m0 6v6M4.22 4.22l4.24 4.24m5.08 5.08l4.24 4.24M1 12h6m6 0h6M4.22 19.78l4.24-4.24m5.08-5.08l4.24-4.24"
        }
      },
      {
        "type": "circle",
        "props": {
          "cx": "12",
          "cy": "12",
          "r": "3"
        }
      }
    ]
  },
  "SHOPPING_CART": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"
        }
      },
      {
        "type": "circle",
        "props": {
          "cx": "9",
          "cy": "21",
          "r": "1"
        }
      },
      {
        "type": "circle",
        "props": {
          "cx": "20",
          "cy": "21",
          "r": "1"
        }
      }
    ]
  },
  "BADGE_V2": {
    "viewBox": "0 0 16 16",
    "children": [
      {
        "type": "circle",
        "props": {
          "cx": "8",
          "cy": "8",
          "r": "8",
          "fill": "currentColor"
        }
      }
    ]
  },
  "BELL_V2": {
    "viewBox": "0 0 24 24",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M12 2C7.58 2 4 5.58 4 11v6.5l-2 2v1h16v-1l-2-2V11c0-5.42-3.58-9-8-9zm0 18c1.1 0 2-.9 2-2h-4c0 1.1.89 2 2 2z",
          "fill": "currentColor"
        }
      }
    ]
  },
  "LOCK_V2": {
    "viewBox": "0 0 16 16",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M4 7V5C4 2.24 5.79 1 8 1s4 1.24 4 5v2h1v8H3V7h1zm2 0h4V5c0-1.66-.9-3-2-3s-2 1.34-2 3v2z",
          "fill": "currentColor"
        }
      }
    ]
  },
  "TREE_V2": {
    "viewBox": "0 0 40 40",
    "children": [
      {
        "type": "path",
        "props": {
          "d": "M20 2L28 12L32 10L30 20L36 18L28 22L32 32L20 28L8 32L12 22L4 24L10 20L8 10L12 12Z",
          "fill": "currentColor",
          "stroke": "#2E7D32",
          "strokeWidth": "1"
        }
      },
      {
        "type": "rect",
        "props": {
          "x": "18",
          "y": "26",
          "width": "4",
          "height": "10",
          "fill": "currentColor"
        }
      }
    ]
  }
};

export type IconKey = keyof typeof SVG_CONTENT;
