require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.4'

target 'FoxEcomExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    react_native_post_install(installer)

    # Skip FBReactNativeSpec codegen build phase (incompatible with Xcode 26+)
    installer.pods_project.targets.each do |target|
      if target.name == 'FBReactNativeSpec'
        target.build_phases.each do |phase|
          if phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
            if phase.shell_script.include?('react-native-codegen') || phase.name.include?('Generate')
              target.build_phases.delete(phase)
            end
          end
        end
      end
    end
  end
end
