/**
 * Generate icons TypeScript file from SVG files
 * Parses SVG and converts to SvgNode structure
 */

const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.join(__dirname, '../src/assets/icons');
const OUTPUT_FILE = path.join(__dirname, '../src/assets/icons/generated-icons.ts');

// Simple regex-based SVG parser
function parseSvgFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');

  // Extract viewBox
  const viewBoxMatch = content.match(/viewBox="([^"]*)"/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';

  // Extract all SVG elements
  const children = [];

  // Parse <path> elements
  const pathRegex = /<path[^>]*>/g;
  let match;
  while ((match = pathRegex.exec(content)) !== null) {
    const pathStr = match[0];
    const props = {};

    // Extract d attribute
    const dMatch = pathStr.match(/d="([^"]*)"/);
    if (dMatch) props.d = dMatch[1];

    // Extract fill
    const fillMatch = pathStr.match(/fill="([^"]*)"/);
    if (fillMatch) props.fill = fillMatch[1];

    // Extract stroke
    const strokeMatch = pathStr.match(/stroke="([^"]*)"/);
    if (strokeMatch) props.stroke = strokeMatch[1];

    // Extract stroke-width
    const swMatch = pathStr.match(/stroke-width="([^"]*)"/);
    if (swMatch) props.strokeWidth = swMatch[1];

    // Extract opacity
    const opMatch = pathStr.match(/opacity="([^"]*)"/);
    if (opMatch) props.opacity = opMatch[1];

    if (props.d) {
      children.push({ type: 'path', props });
    }
  }

  // Parse <polyline> elements
  const polylineRegex = /<polyline[^>]*>/g;
  while ((match = polylineRegex.exec(content)) !== null) {
    const polyStr = match[0];
    const props = {};

    // Extract points
    const pMatch = polyStr.match(/points="([^"]*)"/);
    if (pMatch) props.points = pMatch[1];

    // Extract fill
    const fillMatch = polyStr.match(/fill="([^"]*)"/);
    if (fillMatch) props.fill = fillMatch[1];

    // Extract stroke
    const strokeMatch = polyStr.match(/stroke="([^"]*)"/);
    if (strokeMatch) props.stroke = strokeMatch[1];

    if (props.points) {
      children.push({ type: 'polyline', props });
    }
  }

  // Parse <circle> elements
  const circleRegex = /<circle[^>]*>/g;
  while ((match = circleRegex.exec(content)) !== null) {
    const circStr = match[0];
    const props = {};

    ['cx', 'cy', 'r', 'fill', 'stroke', 'stroke-width', 'opacity'].forEach((attr) => {
      const regex = new RegExp(`${attr}="([^"]*)"`);
      const m = circStr.match(regex);
      if (m) props[attr.replace(/-/g, '')] = m[1];
    });

    if (props.cx || props.cy || props.r) {
      children.push({ type: 'circle', props });
    }
  }

  // Parse <rect> elements
  const rectRegex = /<rect[^>]*>/g;
  while ((match = rectRegex.exec(content)) !== null) {
    const rectStr = match[0];
    const props = {};

    ['x', 'y', 'width', 'height', 'fill', 'stroke', 'stroke-width', 'opacity'].forEach((attr) => {
      const regex = new RegExp(`${attr}="([^"]*)"`);
      const m = rectStr.match(regex);
      if (m) props[attr.replace(/-/g, '')] = m[1];
    });

    children.push({ type: 'rect', props });
  }

  return { viewBox, children };
}

function getIconName(filePath) {
  return path
    .basename(filePath, '.svg')
    .toUpperCase()
    .replace(/-/g, '_');
}

function generateIconsFile() {
  const icons = {};

  // Process main icons
  const mainDir = ICONS_DIR;
  fs.readdirSync(mainDir).forEach((file) => {
    if (file.endsWith('.svg') && file !== 'v2') {
      const filePath = path.join(mainDir, file);
      const iconName = getIconName(file);
      icons[iconName] = parseSvgFile(filePath);
    }
  });

  // Process v2 icons
  const v2Dir = path.join(mainDir, 'v2');
  if (fs.existsSync(v2Dir)) {
    fs.readdirSync(v2Dir).forEach((file) => {
      if (file.endsWith('.svg')) {
        const filePath = path.join(v2Dir, file);
        const iconName = getIconName(file) + '_V2';
        icons[iconName] = parseSvgFile(filePath);
      }
    });
  }

  // Generate TypeScript file
  const output = `/**
 * Generated icon data from SVG files
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-icons.js
 */

export interface SvgNode {
  type: 'path' | 'circle' | 'rect' | 'ellipse' | 'line' | 'polyline' | 'polygon' | 'g';
  props: Record<string, any>;
  children?: SvgNode[];
}

export interface SvgData {
  viewBox: string;
  children: SvgNode[];
}

export const SVG_CONTENT: Record<string, SvgData> = ${JSON.stringify(icons, null, 2)};

export type IconKey = keyof typeof SVG_CONTENT;
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`✅ Generated: ${OUTPUT_FILE}`);
  console.log(`   Icons: ${Object.keys(icons).length}`);
}

generateIconsFile();
